### ISSUE TITLE
DoubletFinder slight modification

### ISSUE THREAD

**Issue by Jayjay601** [xnnba1984/Doublet-Detection-Benchmark#1]
Hi,

Thanks for sharing the codes. When you use DoubletFinder, I think you need to do `FindVariableFeatures `first and then only do `ScaleData`.  Your current code is showing the other way around.
This was discussed [here ](https://github.com/chris-mcginnis-ucsf/DoubletFinder/issues/81). 
I tried the correct way and the way where it was reversed, and it turned out that the number of cells labeled correctly as doublets is quite different between the two. However, I have to point out that I only tried this on the demuxlet stimulated dataset.  I am curious to see the comparison of DoubletFinder to other methods if you can fix this!

Thank you!

J

**Comment by xnnba1984** [comment]
> Hi,
> 
> Thanks for sharing the codes. When you use DoubletFinder, I think you need to do `FindVariableFeatures `first and then only do `ScaleData`. Your current code is showing the other way around.
> This was discussed [here ](https://github.com/chris-mcginnis-ucsf/DoubletFinder/issues/81).
> I tried the correct way and the way where it was reversed, and it turned out that the number of cells labeled correctly as doublets is quite different between the two. However, I have to point out that I only tried this on the demuxlet stimulated dataset. I am curious to see the comparison of DoubletFinder to other methods if you can fix this!
> 
> Thank you!
> 
> J

Hi J,

Thank you for mentioning this change. 

I try the method you showed by switching these two lines. I found the performance is actually down on average. For example, on the 16 real datasets, the mean AUPRC went from 0.537 to 0.458. 

If you check the original DoubletFinder paper, the order is scale->find variable genes (box 1). 

Hope this information is helpful.
