### ISSUE TITLE
Minor Questions/Comments About Manuscript Text (Xi and Li 2021)

### ISSUE THREAD

**Issue by cwarden45** [xnnba1984/Doublet-Detection-Benchmark#3]
Hi,

Thank you very much for putting together this article and GitHub content!

The journal didn't have a comment section, and I think some authors believe PubPeer has a negative connotation.

I think I will also have at least one additional post related to the analysis, but I thought I should first start asking about what is [within the text of the paper](https://www.sciencedirect.com/science/article/pii/S2405471220304592):

***Example 1)*** I think the subsection for "**cxds, bcds and hybrid**" is not formatted correctly?  I used the [Bioconductor version](https://www.bioconductor.org/packages/release/bioc/html/scds.html), but I was not sure if there might also be any version information potentially missing for **scds**.

*~~~Current~~~*:
**Scrublet**: R package *reticulate* (v 1.16) was used to execute the python module *scrublet* (v 0.2.1). The parameters were set by following the instruction at

https://github.com/AllonKleinLab/scrublet/blob/master/examples/scrublet_basics.ipynb.

Doublet scores were obtained from the function *Scrublet.scrub_doublets*. cxds, bcds and hybrid: These three methods were executed by following the instructions at https://github.com/kostkalab/scds.

*~~~Alternative~~~*:
**Scrublet**: R package *reticulate* (v 1.16) was used to execute the python module *scrublet* (v 0.2.1). The parameters were set by following the instruction at

https://github.com/AllonKleinLab/scrublet/blob/master/examples/scrublet_basics.ipynb.

Doublet scores were obtained from the function *Scrublet.scrub_doublets*.

**cxds, bcds and hybrid**: These three methods were executed by following the instructions at https://github.com/kostkalab/scds.

***Example 2)***  In the section "*Computational Efficiency, Scalability, Stability, and Software Implementation of Doublet-Detection Methods*", you say "*First, we summarized the running time of the nine doublet-detection methods (including their required data preprocessing steps; [STAR Methods](https://www.sciencedirect.com/science/article/pii/S2405471220304592?via%3Dihub#sec4)) on the 16 real scRNA-seq datasets in [Table S1](https://www.sciencedirect.com/science/article/pii/S2405471220304592?via%3Dihub#mmc1).*"

However, I think you meant **Table S10**?

I don't believe that I see run-times for *Table S1*.

Thanks Again,
Charles

**Comment by xnnba1984** [comment]
> 

Hi Charles,

Thank you for your comments. I checked the published text and realized that you are right. I find my original version does include the scds information, and also the running time should be in current table S10. The original information for scds is

cxds, bcds and hybrid: These three methods were executed by following the instructions at 
https://github.com/kostkalab/scds.
Doublet scores were obtained from the functions cxds, bcds and cxds_bcds_hybrid in R package scds (v 1.2.0) with parameters set to default.

I suspect the errors may be caused in the journal editing process. But still thanks a lot for pointing out these two issues!

**Comment by cwarden45** [comment]
Thank you very much for confirming.

I also see that the 2nd sentence is already in the methods section.

I am not sure what is the best way to communicate this to other readers.  However, I will close this ticket and work on putting together the separate post related to the analysis part.

Best Wishes,
Charles
